### ISSUE TITLE
Make fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by SirTempest** [xenserver/buildroot#647]
Trying to compile on Ubuntu 14.04 fails due to file not found in _build/SRPMS, despite the files existing in SRPMS. First one happens right off the bat with:
`libre-ocaml_1.2.2-1.dsc`
 
Symlinking the file in SRPMS to _build/SRPMS seems to work, until make runs into another file not found error.

**Comment by kzyczenko** [comment]
Try following:
`cd buildroot`
`rm -rf _build/SRPMS _build/RPMS`
`ln -s RPMS _build/RPMS`
`ln -s SRPMS _build/SRPMS`

**Comment by SirTempest** [comment]
In the mean time I did that, and it was seeming to well for awhile until it ran into another error:
```
[MAKEDEB] _build/SRPMS/liblwt-ocaml_2.4.8-1.dsc
2.4.5-1
2.4.4-1
2.4.3-1
2.2.0-2
2.2.0-2
2.2.0-1
2.0.0-0.3.rc1
2.0.0-0.2.rc1.fc13
2.0.0-0.rc1.fc13
1.1.0-6
1.1.0-5
2.4.8-1
1.1.0-4
1.1.0-3
1.1.0-2
1.1.0-1
cd /tmp/makedeb71CXsF
dpkg-source -b -auto-commit lwt-2.4.8
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../liblwt-ocaml_2.4.5.orig.tar.{bz2,gz,lzma,xz}
Traceback (most recent call last):
    File "/usr/bin/planex-makedeb", line 9, in (module)
        load_entry_point('planex==0.6.0', 'console_scripts', 'planex-makedeb')()
    File "/usr/lib/python2.7/dist-packages/planex/makedeb.py", line 174, in main
        assert res == 0
AssertionError
make: *** [_build/SRPMS/liblwt-ocaml_2.4.8-1.dsc] Error 1
```

I did a `find

**Comment by kzyczenko** [comment]
`sed -i 's/2.4.5/2.4.8/g' SPECS/ocaml-lwt.spec`

But it will fail again on something else. I was not able to compile it successfuly under Ubuntu 14.04.

**Comment by djmoonshine** [comment]
I got the exact same issues.  First the "file not found" issue which the linking of SRPMS and RPMS resolves, and after that the issue with liblwt-ocaml_2.4.8-1.dsc 
I am usning a fresh install of Ubuntu 14.04.2 on a Citrix XenServer to test things out, cound this affect?
