### ISSUE TITLE
Error: Cannot find file biniou.cmxa

### ISSUE THREAD

**Issue by wZi** [xenserver/buildroot#680]
#### console info:
```
 ERROR: Exception(_build/SRPMS/ocaml-qmp-0.9.2-2.el7.centos.src.rpm) Config(epel-7-x86_64) 0 minutes 16 seconds
ERROR: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/ocaml-qmp.spec 
make: *** [_build/RPMS/x86_64/ocaml-qmp-0.9.2-2.el7.centos.x86_64.rpm]  error 1
```
#### the build.log:
 ```
[CMD]: /usr/bin/ocamldep.opt -I lib_test -I dist/build/autogen -modules lib_test/messages.ml
  Messages depends on Arg,Filename,List,OUnit,Printf,Qmp,String
  Messages internally depends on
[1 of 1] Compiling Messages
  [CMD]: /usr/bin/ocamlopt.opt -I dist/build/messages -I dist/build/autogen -I lib_test -I /usr/lib64/ocaml -I /usr/lib64/ocaml/easy-format -I /usr/lib64/ocaml/biniou -I /usr/lib64/ocaml/yojson -I dist/build/lib-qmp -I /usr/lib64/ocaml/oUnit -I /usr/lib64/ocaml/oUnit -bin-annot -o dist/build/messages/messages.cmx -c lib_test/messages.ml
schedule finished: #processes=1 max_concurrency=1
  compilation order: Messages
  self deps: qmp
package deps: [unix,easy-format,biniou,yojson,qmp,oUnit.advanced,oUnit]
Linking executable dist/build/messages/messages
  [CMD]: /usr/bin/ocamlopt.opt -o dist/build/messages/messages -I dist/build/messages -I /usr/lib64/ocaml -I /usr/lib64/ocaml/easy-format -I /usr/lib64/ocaml/biniou -I /usr/lib64/ocaml/yojson -I dist/build/lib-qmp -I /usr/lib64/ocaml/oUnit -I /usr/lib64/ocaml/oUnit unix.cmxa easy_format.cmx biniou.cmxa yojson.cmx qmp.cmxa oUnitAdvanced.cmxa oUnit.cmxa -cclib -Ldist/build/lib-qmp messages.cmx
File "_none_", line 1:
Error: Cannot find file biniou.cmxa
make: *** [build] Error 7
```

Should I build the biniou.cmxa by myself?
Give me the hand~~~
T_T

**Comment by simonjbeaumont** [comment]
> Should I build the biniou.cmxa by myself?

No, it's probably a missing dependency from the the ocaml-qmp spec file. It looks like ocaml-qmp is using obuild which we've seen issues with (with ocaml-qmp actually) when it comes to dependency analysis. I'll see if I can upgrade it to use Oasis and bump a new release.

**Comment by simonjbeaumont** [comment]
https://github.com/xapi-project/ocaml-qmp/pull/5

**Comment by wZi** [comment]
Tks : )

**Comment by simonjbeaumont** [comment]
There's also this: https://github.com/xenserver/buildroot/pull/681

But I'm not sure it will solve the issue. A definite improvement to move from obuild to oasis even if it doesn't.

**Comment by simonjbeaumont** [comment]
They're both merged now. Not sure if they've solved your issue because I haven't rebuilt buildroot from scratch again yet but you can try if you get there before me.

**Comment by wZi** [comment]
I am trying now~~thank you very much~~~

**Comment by wZi** [comment]
so sad,it don't work:
log like that
```
File "_none_", line 1:
Error: Cannot find file /usr/lib64/ocaml/biniou/biniou.cmxa
Command exited with code 2.
E: Failure("Command ''/usr/bin/ocamlbuild' lib/qmp.cma lib/qmp.cmxa lib/qmp.a lib/qmp.cmxs cli/cli.native -tag debug' terminated with error code 10")
```

**Comment by Zahatric** [comment]
I'm receiving the same error on CentOS 6.7. The good news is that this is fixed on the xapi side as opam install xapi now builds correctly. Unsure how to translate that over to buildroot though.

**Comment by simonjbeaumont** [comment]
@Zahatric when you install via opam it installs all the dependencies and the opam packages do not distinguish between base and devel subpackages. Also transitive dependencies are picked up by default. In buildroot we use mock for each package we build so we only install the dependencies specified in the spec file. If there's a hidden dependency that isn't exposed through the transitive closure then we're boned.

It looks like ocaml-qmp is only using yojson so it should be enough to depend on ocaml-yojson-devel but I think that the Yojson module actually requires biniou to be present. It could be an issue with the way we're packaging yojson?

We could work around this by adding a dependency on biniou to qmp but it feels a bit of a hack.

@euanh, any ideas?

**Comment by Zahatric** [comment]
Tried adding:
BuildRequires:  ocaml-biniou-devel to ocaml.qmp.spec

then got new errors relating to an ocaml-easy-format dependency.

Added:
BuildRequires:  ocaml-easy-format-devel to ocaml.qmp.spec

This made a little progress but surfaced more errors that prevent ocaml-qmp from building.

>cp: cannot create regular file '/usr/local/bin/cli': Permission denied
>E: Failure("Command ''cp' '/builddir/build/BUILD/ocaml-qmp-0.9.3/_build/cli/cli.native' '/usr/local/bin/cli'' terminated with error code 1")

Log follows:

Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.4moovx
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf ocaml-qmp-0.9.3
+ /usr/bin/gzip -dc /builddir/build/SOURCES/ocaml-qmp-0.9.3.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd ocaml-qmp-0.9.3
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.e8R9xZ
+ umask 022
+ cd /builddir/build/BUILD
+ cd ocaml-qmp-0.9.3
+ make
oasis setup
ocaml setup.ml -configure 
Configuration: 
ocamlfind: ........................................... /usr/bin/ocamlfind
ocamlc: .............................................. /usr/bin/ocamlc.opt
ocamlopt: ............................................ /usr/bin/ocamlopt.opt
ocamlbuild: .......................................... /usr/bin/ocamlbuild
Package name: ........................................ qmp
Package version: ..................................... 0.9.3
os_type: ............................................. Unix
system: .............................................. linux
architecture: ........................................ amd64
ccomp_type: .......................................... cc
ocaml_version: ....................................... 4.01.1
standard_library_default: ............................ /usr/lib64/ocaml
standard_library: .................................... /usr/lib64/ocaml
standard_runtime: .................................... /usr/bin/ocamlrun
bytecomp_c_compiler: ................................. gcc -fno-defer-pop -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fno-strict-aliasing -fPIC
native_c_compiler: ................................... gcc -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fno-strict-aliasing
model: ............................................... default
ext_obj: ............................................. .o
ext_asm: ............................................. .s
ext_lib: ............................................. .a
ext_dll: ............................................. .so
default_executable_name: ............................. a.out
systhread_supported: ................................. true
Install architecture-independent files dir: .......... /usr/local
Install architecture-dependent files in dir: ......... $prefix
User executables: .................................... $exec_prefix/bin
System admin executables: ............................ $exec_prefix/sbin
Program executables: ................................. $exec_prefix/libexec
Read-only single-machine data: ....................... $prefix/etc
Modifiable architecture-independent data: ............ $prefix/com
Modifiable single-machine data: ...................... $prefix/var
Object code libraries: ............................... $exec_prefix/lib
Read-only arch-independent data root: ................ $prefix/share
Read-only architecture-independent data: ............. $datarootdir
Info documentation: .................................. $datarootdir/info
Locale-dependent data: ............................... $datarootdir/locale
Man documentation: ................................... $datarootdir/man
Documentation root: .................................. $datarootdir/doc/$pkg_name
HTML documentation: .................................. $docdir
DVI documentation: ................................... $docdir
PDF documentation: ................................... $docdir
PS documentation: .................................... $docdir
findlib_version: ..................................... 1.5.5
is_native: ........................................... true
suffix_program: ...................................... 
Remove a file.: ...................................... rm -f
Remove a directory.: ................................. rm -rf
Turn ocaml debug flag on: ............................ true
Turn ocaml profile flag on: .......................... false
Compiler support generation of .cmxs.: ............... true
OCamlbuild additional flags: ......................... 
Create documentations: ............................... true
Compile tests executable and library and run them: ... false
pkg_yojson: .......................................... /usr/lib64/ocaml/yojson
pkg_unix: ............................................ /usr/lib64/ocaml
pkg_cmdliner: ........................................ /usr/lib64/ocaml/cmdliner
ocaml setup.ml -build 
/usr/bin/ocamlopt.opt unix.cmxa -I /usr/lib64/ocaml/ocamlbuild /usr/lib64/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/lib64/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
/usr/bin/ocamlfind ocamldep -package unix -package yojson -modules lib/qmp.mli > lib/qmp.mli.depends
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp.cmi lib/qmp.mli
/usr/bin/ocamlfind ocamldep -package unix -package yojson -modules lib/qmp.ml > lib/qmp.ml.depends
/usr/bin/ocamlfind ocamldep -package unix -package yojson -modules lib/qmp_protocol.mli > lib/qmp_protocol.mli.depends
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp_protocol.cmi lib/qmp_protocol.mli
/usr/bin/ocamlfind ocamldep -package unix -package yojson -modules lib/qmp_protocol.ml > lib/qmp_protocol.ml.depends
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp.cmo lib/qmp.ml
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp_protocol.cmo lib/qmp_protocol.ml
/usr/bin/ocamlfind ocamlc -a -warn-error +1..45 lib/qmp.cmo lib/qmp_protocol.cmo -o lib/qmp.cma
/usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp.cmx lib/qmp.ml
/usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp_protocol.cmx lib/qmp_protocol.ml
/usr/bin/ocamlfind ocamlopt -a -warn-error +1..45 lib/qmp.cmx lib/qmp_protocol.cmx -o lib/qmp.cmxa
/usr/bin/ocamlfind ocamlopt -shared lib/qmp.cmxa lib/qmp.cmx lib/qmp_protocol.cmx -o lib/qmp.cmxs
/usr/bin/ocamlfind ocamldep -package cmdliner -package unix -package yojson -modules cli/cli.ml > cli/cli.ml.depends
/usr/bin/ocamlfind ocamldep -package cmdliner -package unix -package yojson -modules cli/client.mli > cli/client.mli.depends
/usr/bin/ocamlfind ocamldep -package cmdliner -package unix -package yojson -modules cli/common.ml > cli/common.ml.depends
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/common.cmo cli/common.ml
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/client.cmi cli/client.mli
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/cli.cmo cli/cli.ml
/usr/bin/ocamlfind ocamldep -package cmdliner -package unix -package yojson -modules cli/client.ml > cli/client.ml.depends
/usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/common.cmx cli/common.ml
/usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/client.cmx cli/client.ml
/usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/cli.cmx cli/cli.ml
/usr/bin/ocamlfind ocamlopt -g -warn-error +1..45 -linkpkg -package cmdliner -package unix -package yojson cli/common.cmx lib/qmp.cmxa cli/client.cmx cli/cli.cmx -o cli/cli.native
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.SJM3Zz
+ umask 022
+ cd /builddir/build/BUILD
+ '[' /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64 '!=' / ']'
+ rm -rf /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64
++ dirname /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64
+ mkdir -p /builddir/build/BUILDROOT
+ mkdir /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64
+ cd ocaml-qmp-0.9.3
+ export OCAMLFIND_DESTDIR=/builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml
+ OCAMLFIND_DESTDIR=/builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml
+ mkdir -p /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml
+ make install DESTDIR=/builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml
ocaml setup.ml -install 
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.mli
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.mli
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cma
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmxa
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.a
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmxs
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.cmi
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.cmti
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.cmt
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.annot
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmi
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmti
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmt
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.annot
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.cmx
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmx
Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/META
cp: cannot create regular file '/usr/local/bin/cli': Permission denied
E: Failure("Command ''cp' '/builddir/build/BUILD/ocaml-qmp-0.9.3/_build/cli/cli.native' '/usr/local/bin/cli'' terminated with error code 1")
make: *** [install] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.SJM3Zz (%install)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.SJM3Zz (%install)
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/ocaml-qmp.spec 
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.6/site-packages/mockbuild/util.py", line 520, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/ocaml-qmp.spec 
LEAVE do --> EXCEPTION RAISED

**Comment by simonjbeaumont** [comment]
Sounds like these libraries might just be a bit pants. I'm not a packaging expert but it sounds like we're in a bit of a dependency mess. From the final error you mention it sounds like you might have cracked the dependency problem now the make install target failed for qmp.

Good progress. I'll try and find some time tomorrow to look at that. Unless you solve it in the meantime.

-- simon.beaumont@citrix.com<mailto:simon.beaumont@citrix.com> (via iPhone)

On 9 Nov 2015, at 18:17, Zahatric <notifications@github.com<mailto:notifications@github.com>> wrote:


Tried adding:
BuildRequires: ocaml-biniou-devel to ocaml.qmp.spec

then got new errors relating to an ocaml-easy-format dependency.

Added:
BuildRequires: ocaml-easy-format-devel to ocaml.qmp.spec

This made a little progress but surfaced more errors that prevent ocaml-qmp from building.

cp: cannot create regular file '/usr/local/bin/cli': Permission denied
E: Failure("Command ''cp' '/builddir/build/BUILD/ocaml-qmp-0.9.3/_build/cli/cli.native' '/usr/local/bin/cli'' terminated with error code 1")

Log follows:

Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.4moovx

  *   umask 022
  *   cd /builddir/build/BUILD
  *   cd /builddir/build/BUILD
  *   rm -rf ocaml-qmp-0.9.3
  *   /usr/bin/gzip -dc /builddir/build/SOURCES/ocaml-qmp-0.9.3.tar.gz
  *   /usr/bin/tar -xf -
  *   STATUS=0
  *   '[' 0 -ne 0 ']'
  *   cd ocaml-qmp-0.9.3
  *   /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
  *   exit 0 Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.e8R9xZ
  *   umask 022
  *   cd /builddir/build/BUILD
  *   cd ocaml-qmp-0.9.3
  *   make oasis setup ocaml setup.ml -configure Configuration: ocamlfind: ........................................... /usr/bin/ocamlfind ocamlc: .............................................. /usr/bin/ocamlc.opt ocamlopt: ............................................ /usr/bin/ocamlopt.opt ocamlbuild: .......................................... /usr/bin/ocamlbuild Package name: ........................................ qmp Package version: ..................................... 0.9.3 os_type: ............................................. Unix system: .............................................. linux architecture: ........................................ amd64 ccomp_type: .......................................... cc ocaml_version: ....................................... 4.01.1 standard_library_default: ............................ /usr/lib64/ocaml standard_library: .................................... /usr/lib64/ocaml standard_runtime: .................................... /usr/bin/ocamlrun bytecomp_c_compiler: ................................. gcc -fno-defer-pop -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fno-strict-aliasing -fPIC native_c_compiler: ................................... gcc -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fno-strict-aliasing model: ............................................... default ext_obj: ............................................. .o ext_asm: ............................................. .s ext_lib: ............................................. .a ext_dll: ............................................. .so default_executable_name: ............................. a.out systhread_supported: ................................. true Install architecture-independent files dir: .......... /usr/local Install architecture-dependent files in dir: ......... $prefix User executables: .................................... $exec_prefix/bin System admin executables: ............................ $exec_prefix/sbin Program executables: ................................. $exec_prefix/libexec Read-only single-machine data: ....................... $prefix/etc Modifiable architecture-independent data: ............ $prefix/com Modifiable single-machine data: ...................... $prefix/var Object code libraries: ............................... $exec_prefix/lib Read-only arch-independent data root: ................ $prefix/share Read-only architecture-independent data: ............. $datarootdir Info documentation: .................................. $datarootdir/info Locale-dependent data: ............................... $datarootdir/locale Man documentation: ................................... $datarootdir/man Documentation root: .................................. $datarootdir/doc/$pkg_name HTML documentation: .................................. $docdir DVI documentation: ................................... $docdir PDF documentation: ................................... $docdir PS documentation: .................................... $docdir findlib_version: ..................................... 1.5.5 is_native: ........................................... true suffix_program: ...................................... Remove a file.: ...................................... rm -f Remove a directory.: ................................. rm -rf Turn ocaml debug flag on: ............................ true Turn ocaml profile flag on: .......................... false Compiler support generation of .cmxs.: ............... true OCamlbuild additional flags: ......................... Create documentations: ............................... true Compile tests executable and library and run them: ... false pkg_yojson: .......................................... /usr/lib64/ocaml/yojson pkg_unix: ............................................ /usr/lib64/ocaml pkg_cmdliner: ........................................ /usr/lib64/ocaml/cmdliner ocaml setup.ml -build /usr/bin/ocamlopt.opt unix.cmxa -I /usr/lib64/ocaml/ocamlbuild /usr/lib64/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/lib64/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild /usr/bin/ocamlfind ocamldep -package unix -package yojson -modules lib/qmp.mli > lib/qmp.mli.depends /usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp.cmi lib/qmp.mli /usr/bin/ocamlfind ocamldep -package unix -package yojson -modules lib/qmp.ml > lib/qmp.ml.depends /usr/bin/ocamlfind ocamldep -package unix -package yojson -modules lib/qmp_protocol.mli > lib/qmp_protocol.mli.depends /usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp_protocol.cmi lib/qmp_protocol.mli /usr/bin/ocamlfind ocamldep -package unix -package yojson -modules lib/qmp_protocol.ml > lib/qmp_protocol.ml.depends /usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp.cmo lib/qmp.ml /usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp_protocol.cmo lib/qmp_protocol.ml /usr/bin/ocamlfind ocamlc -a -warn-error +1..45 lib/qmp.cmo lib/qmp_protocol.cmo -o lib/qmp.cma /usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp.cmx lib/qmp.ml /usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -warn-error +1..45 -package unix -package yojson -I lib -o lib/qmp_protocol.cmx lib/qmp_protocol.ml /usr/bin/ocamlfind ocamlopt -a -warn-error +1..45 lib/qmp.cmx lib/qmp_protocol.cmx -o lib/qmp.cmxa /usr/bin/ocamlfind ocamlopt -shared lib/qmp.cmxa lib/qmp.cmx lib/qmp_protocol.cmx -o lib/qmp.cmxs /usr/bin/ocamlfind ocamldep -package cmdliner -package unix -package yojson -modules cli/cli.ml > cli/cli.ml.depends /usr/bin/ocamlfind ocamldep -package cmdliner -package unix -package yojson -modules cli/client.mli > cli/client.mli.depends /usr/bin/ocamlfind ocamldep -package cmdliner -package unix -package yojson -modules cli/common.ml > cli/common.ml.depends /usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/common.cmo cli/common.ml /usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/client.cmi cli/client.mli /usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/cli.cmo cli/cli.ml /usr/bin/ocamlfind ocamldep -package cmdliner -package unix -package yojson -modules cli/client.ml > cli/client.ml.depends /usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/common.cmx cli/common.ml /usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/client.cmx cli/client.ml /usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -I lib -warn-error +1..45 -package cmdliner -package unix -package yojson -I cli -I lib -o cli/cli.cmx cli/cli.ml /usr/bin/ocamlfind ocamlopt -g -warn-error +1..45 -linkpkg -package cmdliner -package unix -package yojson cli/common.cmx lib/qmp.cmxa cli/client.cmx cli/cli.cmx -o cli/cli.native
  *   exit 0 Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.SJM3Zz
  *   umask 022
  *   cd /builddir/build/BUILD
  *   '[' /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64 '!=' / ']'
  *   rm -rf /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64 ++ dirname /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64
  *   mkdir -p /builddir/build/BUILDROOT
  *   mkdir /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64
  *   cd ocaml-qmp-0.9.3
  *   export OCAMLFIND_DESTDIR=/builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml
  *   OCAMLFIND_DESTDIR=/builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml
  *   mkdir -p /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml
  *   make install DESTDIR=/builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml ocaml setup.ml -install Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.mli Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.mli Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cma Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmxa Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.a Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmxs Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.cmi Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.cmti Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.cmt Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.annot Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmi Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmti Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmt Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.annot Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp_protocol.cmx Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/qmp.cmx Installed /builddir/build/BUILDROOT/ocaml-qmp-0.9.3-1.el7.centos.x86_64//usr/lib64/ocaml/qmp/META cp: cannot create regular file '/usr/local/bin/cli': Permission denied E: Failure("Command ''cp' '/builddir/build/BUILD/ocaml-qmp-0.9.3/_build/cli/cli.native' '/usr/local/bin/cli'' terminated with error code 1") make: *** [install] Error 1 error: Bad exit status from /var/tmp/rpm-tmp.SJM3Zz (%install) RPM build errors: Bad exit status from /var/tmp/rpm-tmp.SJM3Zz (%install) Child return code was: 1 EXCEPTION: Command failed. See logs for output. # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/ocaml-qmp.spec Traceback (most recent call last): File "/usr/lib/python2.6/site-packages/mockbuild/trace_decorator.py", line 84, in trace result = func(args, *kw) File "/usr/lib/python2.6/site-packages/mockbuild/util.py", line 520, in do raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode) Error: Command failed. See logs for output. # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/ocaml-qmp.spec LEAVE do --> EXCEPTION RAISED

**Comment by samoht** [comment]
Would maybe be easier to get the metadata from opam ...

**Comment by simonjbeaumont** [comment]
@samoht I'm not sure. I think it might be a packaging error in buildroot for one of the packages up the chain. We can see in the spam file for qmp that it doesn't need a direct dependency on biniou: https://github.com/ocaml/opam-repository/blob/19aff7aa98c0762ccebc57b59313bcda564611e7/packages/qmp/qmp.0.9.1/opam

I suspect maybe there's something missing in our ocaml-yojson-devel package. Unless I misunderstood your suggestion?
