### ISSUE TITLE
Building xapi on CentOS 7 gives error.

### ISSUE THREAD

**Issue by teodino93** [xenserver/buildroot#684]
In the make process building xapi gives an error:
[FETCH] _build/SOURCES/xen-api-1.9.80.tar.gz
[MOCK] _build/SRPMS/xapi-1.9.80-2.el7.centos.src.rpm
ERROR: Exception(_build/SRPMS/xapi-1.9.80-2.el7.centos.src.rpm) Config(epel-7-x86_64) 2 minutes 13 seconds
ERROR: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/xapi.spec
make: **\* [_build/RPMS/x86_64/xapi-python-devel-1.9.80-2.el7.centos.x86_64.rpm] Errore 1

Followed the readme, installed the requirements, cloned the git and ./configure.

In the zip the build.log.
[build.zip](https://github.com/xenserver/buildroot/files/113916/build.zip)

**Comment by buzzheavyyear** [comment]
likely to be the same as :

http://lists.xen.org/archives/html/xen-api/2016-01/msg00000.html

Date: Tue, 2 Feb 2016 04:51:13 -0800

**Comment by teodino93** [comment]
No, I don't think it's the same, i have can't get rootid in root.log, but i think it's ignorable, the real error it's in the build.log and it's related to Omake.

File "quicktest.ml", line 855, characters 1-30:
Error: Unbound value Stunnel.set_good_ciphersuites
**\* omake: 1903/2320 targets are up to date
**\* omake: failed (31.93 sec, 415/467 scans, 325/798 rules, 1085/3108 digests)
**\* omake: targets were not rebuilt because of errors:
   ocaml/xapi/quicktest.cmi
      depends on: ocaml/xapi/quicktest.ml
   ocaml/xapi/quicktest.cmx
      depends on: ocaml/xapi/quicktest.ml
   ocaml/xapi/quicktest.o
      depends on: ocaml/xapi/quicktest.ml
make: **\* [all] Error 2

**Comment by thomassa** [comment]
set_good_ciphersuites is one of a pair of functions added to the Stunnel module recently:
xapi-project/xen-api-libs-transitional#23
So `Error: Unbound value Stunnel.set_good_ciphersuites` shows that an older Stunnel is still being used.

**Comment by teodino93** [comment]
Resolved making Mock build the latest commit of xen-api-libs-transitional, now it gives this error:

File "cpuid_helpers.ml", line 113, characters 22-54:
Error: Unbound value Client.HOST.upgrade_cpu_features
**\* omake: 1967/2320 targets are up to date
**\* omake: failed (34.17 sec, 415/467 scans, 348/862 rules, 1149/3236 digests)
**\* omake: targets were not rebuilt because of errors:
   ocaml/xapi/cpuid_helpers.cmx
      depends on: ocaml/xapi/cpuid_helpers.ml
   ocaml/xapi/cpuid_helpers.o
      depends on: ocaml/xapi/cpuid_helpers.ml
make: **\* [all] Error 2
errore: Stato d'uscita errato da /var/tmp/rpm-tmp.u3O0rs (%build)
Errori di compilazione RPM:
    Stato d'uscita errato da /var/tmp/rpm-tmp.u3O0rs (%build)
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/xapi.spec
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 526, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/xapi.spec
LEAVE do --> EXCEPTION RAISED

**Comment by euanh** [comment]
This failure is because xen-api-libs-transitional's latest release depends on changes in CPU feature handling which are not yet in upstream Xen.   We don't currently have a good strategy for handling features which have been added to Xapi but have not yet made it upstream.

Why are you trying to build Xapi?   If you eventually plan to install the packages on a Xenserver-based system, take a look at http://xenserver.org/blog.html?view=entry&id=109.  The approach described there does use the XenServer Xen patch queue, so the CPU feature handling code will be present.

**Comment by buzzheavyyear** [comment]
Why are you trying to build Xapi?

I'm trying to build images for arm sbc's using centos, xen and xapi - there are a couple of ubuntu based images, which contain xapi - http://blobs.openmirage.org . The version of xapi used in the images is pretty old. I'm just about to spend some time on a Pine64 and I'd love to get xapi running on that too.

Thanks for the pointer to Jon's blog - I'll give it a try sometime next week and see if I can get xapi up and running on a cubietruck.

**Comment by teodino93** [comment]
I'm trying to build xapi in a CentOS environment just to know if it's possible to have it run in Xen-4.4 and eventually in Xen-4.6, but not with XenServer.
